#!/usr/bin/env python3
"""
One-time backfill of videos that had already scrolled out of TikTok's
10-item embed window before this site existed.

TikTok's profile grid loads through a signed internal API, so there is no
polite way to enumerate an account's full history - but we don't need one:
the ratings spreadsheet links every video it covered, so data/ratings.js
already holds the IDs. This script fetches each missing video's own page once
(caption, view count, post time, cover image), writes it into data/site.js,
and never needs to run again: from here on the 5-a-day updater catches every
new video while it is still inside the embed window.

Usage:
  python3 scripts/backfill.py            # fetch whatever is missing
  python3 scripts/backfill.py --dry-run  # just list what it would fetch
"""

from __future__ import annotations

import argparse
import json
import random
import re
import sys
import time

# reuse the updater's fetching, categorisation and thumbnail plumbing
sys.path.insert(0, str(__import__("pathlib").Path(__file__).resolve().parent))
from update import (  # noqa: E402
    ASSETS, DATA, HANDLE, categorise, counties_for, created_from_id,
    fetch_thumb, get, load_previous,
)


def known_ids_from_ratings() -> set[str]:
    f = DATA / "ratings.js"
    if not f.exists():
        return set()
    return set(re.findall(r'"videoId":\s*"(\d+)"', f.read_text(encoding="utf-8")))


def fetch_video_record(vid: str) -> dict | None:
    """Everything the site needs for one video, from its own page."""
    try:
        html = get(f"https://www.tiktok.com/@{HANDLE}/video/{vid}", tries=2).decode("utf-8", "ignore")
        m = re.search(r'id="__UNIVERSAL_DATA_FOR_REHYDRATION__"[^>]*>(.*?)</script>', html, re.S)
        if not m:
            print(f"    {vid}: no state blob (anti-bot page?)")
            return None
        item = (json.loads(m.group(1)).get("__DEFAULT_SCOPE__", {})
                .get("webapp.video-detail", {}).get("itemInfo", {}).get("itemStruct", {}))
        if not item:
            print(f"    {vid}: no itemStruct")
            return None
        cap = (item.get("desc") or "").strip()
        cat, label = categorise(cap)
        return {
            "id": vid,
            "cap": cap,
            "views": int((item.get("stats") or {}).get("playCount") or 0),
            "cat": cat,
            "label": label,
            "counties": counties_for(cap),
            "created": item.get("createTime") or created_from_id(vid),
            "cover": (item.get("video") or {}).get("cover"),
        }
    except Exception as e:  # noqa: BLE001
        print(f"    {vid}: {type(e).__name__}: {e}")
        return None


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    prev = load_previous()
    if not prev.get("videos"):
        sys.exit("data/site.js is empty - run scripts/update.py first")

    have = {v["id"] for v in prev["videos"]}
    missing = sorted(known_ids_from_ratings() - have, key=int, reverse=True)
    print(f"{len(have)} videos on the site, {len(missing)} known-but-missing")
    if not missing:
        print("nothing to backfill")
        return 0
    if args.dry_run:
        for vid in missing:
            print(f"  would fetch {vid}")
        return 0

    added = 0
    for i, vid in enumerate(missing):
        if i:
            time.sleep(2 + random.uniform(0, 2))
        print(f"→ {vid} ({i + 1}/{len(missing)})")
        rec = fetch_video_record(vid)
        if not rec:
            continue
        cover = rec.pop("cover", None)
        if not fetch_thumb(vid, cover):
            print("    no thumbnail - holding this one back")
            continue
        prev["videos"].append(rec)
        added += 1
        print(f"    [{rec['label']}] {rec['views']} views  {rec['cap'][:50]!r}")

    if not added:
        print("nothing could be fetched - site.js untouched")
        return 1

    prev["videos"].sort(key=lambda v: int(v["id"]), reverse=True)
    biggest = max(prev["videos"], key=lambda v: v["views"])["id"]
    for v in prev["videos"]:
        v["hot"] = (v["id"] == biggest)
    prev["profile"]["videoCount"] = max(
        prev["profile"].get("videoCount") or 0, len(prev["videos"]))

    (DATA / "site.js").write_text(
        "// Generated by scripts/update.py - do not edit by hand.\n"
        "// To pin a video's category, use data/overrides.json instead.\n"
        "window.SITE_DATA = " + json.dumps(prev, indent=2) + ";\n",
        encoding="utf-8",
    )
    print(f"\n✓ added {added} video(s); site now holds {len(prev['videos'])}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
